# Exclude build directories and generated files
exclude = [
    "build/",
    "dist/",
    "*.egg-info/",
    "__pycache__/",
]

line-length = 88
target-version = "py38"

[lint]
# Enable common linting rules
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]

# Ignore specific rules that may be too strict for this codebase
ignore = [
    "E501",  # Line too long (handled by formatter)
    "B008",  # Do not perform function calls in argument defaults
    "B904",  # raise-without-from-inside-except
]

[lint.per-file-ignores]
# Allow unused imports in __init__.py files
"__init__.py" = ["F401"]
# Be more lenient with test files
"tests/**" = ["B011"]

[lint.isort]
# Keep imports organized and compatible with existing style
known-first-party = ["mycelya_torch"]

[format]
# Use double quotes and standard formatting
quote-style = "double"
indent-style = "space"
